version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=formio_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_admin
    volumes:
      - fomrio_db:/var/lib/postgresql/data
volumes:
  fomrio_db:
    driver: local