# Generated by Django 4.1.3 on 2022-11-23 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='googleOauth',
            field=models.JSONField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
