# Generated by Django 4.1.3 on 2022-11-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_googleoauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailVerified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='googleOauth',
            new_name='google_oauth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registeredAt',
        ),
    ]
