# Generated by Django 4.1.3 on 2022-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_emailverified_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_oauth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
