# Generated by Django 4.1.3 on 2022-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_google_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_oauth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
