# Generated by Django 4.1.3 on 2022-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_oauth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_oauth',
        ),
        migrations.AddField(
            model_name='user',
            name='github_oauth_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_oauth_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
